@startuml
'https://plantuml.com/class-diagram

struct Artist {
+ name : string
}

struct Track {
+ title : string
+ duration : int
+ artists : Artist[]
+ genres : string[]
}
Artist <--o Track

struct Album {
+ title : string
+ artists : Artist[]
+ tracks : Track[]
}
Artist <--o Album
Track <--o Album


@enduml