@startuml
'https://plantuml.com/class-diagram

struct Track {
+ title : string
+ duration : int
+ artists : Artist[]
+ albums : Album[]
+ genres : string[]
}

struct Artist {
+ name : string
+ tracks : Track[]
+ albums : Album[]
+ genres : string[]
}

struct Album {
+ title : string
+ artists : Artist[]
+ tracks : Track[]
+ genres : string[]
}

Artist <--o Track
Artist <--o Album

Album <--o Track
Album <--o Artist

Track <--o Artist
Track <--o Album

@enduml